# ────────────────────────────────────────────────────────────────────────────
# GENERATED by `orch gen-dag alos_dyn` — DO NOT EDIT.
# Source:    orch/workflow/pipelines/alos_dyn.yaml  (11 tasks)
# Settings:  orch/workflow/airflow/dags.yaml
# Generator: version 1
#
# To change the graph, edit the pipeline YAML and re-run `orch gen-dag`.
# To change THIS DAG only, write customize_ALOS_DYN.py in this
# folder (see orch_dag_common.apply_customizations) — the generator
# never touches that file.
# ────────────────────────────────────────────────────────────────────────────
"""ALOS_DYN — generated from the alos_dyn orch pipeline."""

from datetime import datetime

from airflow import DAG
from airflow.utils.task_group import TaskGroup

from orch_dag_common import (
    apply_customizations,
    cleanup_variables_task,
    job_status_task,
    make_failure_callback,
    orch_init_task,
    orch_task,
    set_variables_task,
    slack_tail,
)


DAG_ID = 'ALOS_DYN'
PIPELINE = 'alos_dyn'
REPO = '/home/ubuntu/insarscripts/stack_processor_aws_dev'
WORK_ROOT = '/home/ubuntu/urgent_response'
SETUP_CMD = 'source /home/ubuntu/insarscripts/stack_processor_aws_dev/env_setup/setup_env.sh alos_dyn'
SSH_CONN_ID = 'ssh'
HTTP_CONN_ID = 'sarfinder'
HTTP_ENDPOINT = 'api/sarfinder/airflow/task/update/'
SLACK_CONN_ID = 'slack_webhook_dpm2'
SLACK_CHANNEL = '#dpm2-sarfinder-aws-hpc'
SLACK_MESSAGE = ':blob_excited: ALOS_DYN products are ready. On your MacBook:\n```\nscp -r aws-hpc2:/home/ubuntu/urgent_response/{{ var.json[run_id].dir_name }}/products .\n```\n'


failure_callback = make_failure_callback(
    slack_conn_id=SLACK_CONN_ID,
    slack_channel=SLACK_CHANNEL,
    http_conn_id=HTTP_CONN_ID,
    http_endpoint=HTTP_ENDPOINT,
)


with DAG(
    dag_id=DAG_ID,
    schedule_interval=None,
    start_date=datetime(2022, 1, 1),
    catchup=False,
    default_args={'retries': 0, 'on_failure_callback': failure_callback},
    on_failure_callback=failure_callback,
) as dag:
    # The run payload (dir_name, modes, bbox, dates, …) reaches every
    # task through the run-id Variable this sets.
    t_set_variables = set_variables_task(DAG_ID)

    # step: 00a_prepare_directory
    t_00_prepare_directory = orch_init_task(
        '00_prepare_directory',
        pipeline=PIPELINE,
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # ── top-level pipeline tasks ────────────────────────────────────────────────
    # step: 02a_symlink_data
    t_01_symlink_data = orch_task(
        '01_symlink_data',
        '01_symlink_data',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 03_create_run_script
    t_02_create_run_script = orch_task(
        '02_create_run_script',
        '02_create_run_script',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: exe_run
    t_03_execute_coreg_runs = orch_task(
        '03_execute_coreg_runs',
        '03_execute_coreg_runs',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 04b_stack_publish
    t_04_stack_publish = orch_task(
        '04_stack_publish',
        '04_stack_publish',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 05_generate_sarstack_runfiles
    t_05_generate_runfiles = orch_task(
        '05_generate_runfiles',
        '05_generate_runfiles',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: exe_run   when: run_files/run_params_dask_icors, mode:dpm3
    t_06_run_icors = orch_task(
        '06_run_icors',
        '06_run_icors',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 05b_create_dpm23_runfiles
    t_06_create_dpm23_runfiles = orch_task(
        '06_create_dpm23_runfiles',
        '06_create_dpm23_runfiles',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 06_apply_layovershadow
    t_07_apply_layovershadow = orch_task(
        '07_apply_layovershadow',
        '07_apply_layovershadow',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 08_dpm3_weighted_mean
    t_08_dpm3_weighted_mean = orch_task(
        '08_dpm3_weighted_mean',
        '08_dpm3_weighted_mean',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 93_upload_greyscale
    t_09_upload_greyscale = orch_task(
        '09_upload_greyscale',
        '09_upload_greyscale',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # ── tail ────────────────────────────────────────────────────────────────────
    t_send_slack = slack_tail(
        slack_conn_id=SLACK_CONN_ID,
        slack_channel=SLACK_CHANNEL,
        message=SLACK_MESSAGE,
    )

    t_update_job_status = job_status_task(
        http_conn_id=HTTP_CONN_ID,
        endpoint=HTTP_ENDPOINT,
    )

    t_cleanup_variables = cleanup_variables_task()

    # ── task registry — keyed by ORCH name (see apply_customizations) ───────────
    TASKS = {
        '00_prepare_directory': t_00_prepare_directory,
        '01_symlink_data': t_01_symlink_data,
        '02_create_run_script': t_02_create_run_script,
        '03_execute_coreg_runs': t_03_execute_coreg_runs,
        '04_stack_publish': t_04_stack_publish,
        '05_generate_runfiles': t_05_generate_runfiles,
        '06_run_icors': t_06_run_icors,
        '06_create_dpm23_runfiles': t_06_create_dpm23_runfiles,
        '07_apply_layovershadow': t_07_apply_layovershadow,
        '08_dpm3_weighted_mean': t_08_dpm3_weighted_mean,
        '09_upload_greyscale': t_09_upload_greyscale,
    }

    # ── wiring — mirrors the pipeline `needs:` DAG, one edge per line ───────────
    # Head: nothing can run before the payload is in place.
    t_set_variables >> t_00_prepare_directory

    t_00_prepare_directory >> t_01_symlink_data
    t_01_symlink_data >> t_02_create_run_script
    t_02_create_run_script >> t_03_execute_coreg_runs
    t_03_execute_coreg_runs >> t_04_stack_publish
    t_04_stack_publish >> t_05_generate_runfiles
    t_05_generate_runfiles >> t_06_run_icors
    t_06_run_icors >> t_06_create_dpm23_runfiles
    t_05_generate_runfiles >> t_07_apply_layovershadow
    t_06_create_dpm23_runfiles >> t_08_dpm3_weighted_mean
    t_07_apply_layovershadow >> t_08_dpm3_weighted_mean
    t_06_create_dpm23_runfiles >> t_09_upload_greyscale
    t_08_dpm3_weighted_mean >> t_09_upload_greyscale

    # Tail: every branch tip converges on the notification chain.
    t_09_upload_greyscale >> t_send_slack
    t_send_slack >> t_update_job_status
    t_update_job_status >> t_cleanup_variables

    # Structural per-DAG customization, if the operator wrote a sidecar.
    apply_customizations(dag, TASKS, dag_id=DAG_ID)
