# ────────────────────────────────────────────────────────────────────────────
# GENERATED by `orch gen-dag nisar_dyn` — DO NOT EDIT.
# Source:    orch/workflow/pipelines/nisar_dyn.yaml  (47 tasks)
# Settings:  orch/workflow/airflow/dags.yaml
# Generator: version 2
#
# To change the graph, edit the pipeline YAML and re-run `orch gen-dag`.
# To change THIS DAG only, write customize_NISAR_DYN.py in this
# folder (see orch_dag_common.apply_customizations) — the generator
# never touches that file.
# ────────────────────────────────────────────────────────────────────────────
"""NISAR_DYN — generated from the nisar_dyn orch pipeline."""

from datetime import datetime

from airflow import DAG
from airflow.utils.task_group import TaskGroup

from orch_dag_common import (
    apply_customizations,
    cleanup_variables_task,
    job_status_task,
    make_failure_callback,
    orch_init_task,
    orch_task,
    set_variables_task,
    slack_tail,
)


DAG_ID = 'NISAR_DYN'
PIPELINE = 'nisar_dyn'
REPO = '/home/ubuntu/insarscripts/stack_processor_aws_dev'
WORK_ROOT = '/home/ubuntu/urgent_response'
SETUP_CMD = 'source /home/ubuntu/insarscripts/stack_processor_aws_dev/env_setup/setup_env.sh nisar_dyn'
SSH_CONN_ID = 'ssh'
HTTP_CONN_ID = 'sarfinder'
HTTP_ENDPOINT = 'api/sarfinder/airflow/task/update/'
SLACK_CONN_ID = 'slack_webhook_dpm2'
SLACK_CHANNEL = '#dpm2-sarfinder-aws-hpc'
SLACK_MESSAGE = ':blob_excited: NISAR_DYN products are ready. On your MacBook:\n```\nscp -r aws-hpc2:/home/ubuntu/urgent_response/{{ var.json[run_id].dir_name }}/products .\n```\n'


failure_callback = make_failure_callback(
    slack_conn_id=SLACK_CONN_ID,
    slack_channel=SLACK_CHANNEL,
    http_conn_id=HTTP_CONN_ID,
    http_endpoint=HTTP_ENDPOINT,
)


with DAG(
    dag_id=DAG_ID,
    schedule_interval=None,
    start_date=datetime(2022, 1, 1),
    catchup=False,
    default_args={'retries': 0, 'on_failure_callback': failure_callback},
    on_failure_callback=failure_callback,
) as dag:
    # The run payload (dir_name, modes, bbox, dates, …) reaches every
    # task through the run-id Variable this sets.
    t_set_variables = set_variables_task(DAG_ID)

    # step: 00a_prepare_directory
    t_00_prepare_directory = orch_init_task(
        '00_prepare_directory',
        pipeline=PIPELINE,
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # ── coreg_rslc  (satellite coregistration) ──────────────────────────────────
    with TaskGroup(group_id='coreg_rslc') as tg_coreg_rslc:
        # step: 00b_get_dem   when: $product_type = RSLC
        t_coreg_rslc__01_get_dem = orch_task(
            '01_get_dem',
            'coreg_rslc/01_get_dem',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 01_download   when: $product_type = RSLC
        t_coreg_rslc__02_download = orch_task(
            '02_download',
            'coreg_rslc/02_download',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 02a_symlink_data   when: $product_type = RSLC
        t_coreg_rslc__03_symlink_data = orch_task(
            '03_symlink_data',
            'coreg_rslc/03_symlink_data',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 03_create_run_script   when: $product_type = RSLC
        t_coreg_rslc__04_create_run_script = orch_task(
            '04_create_run_script',
            'coreg_rslc/04_create_run_script',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: $product_type = RSLC
        t_coreg_rslc__coreg_run1 = orch_task(
            'coreg_run1',
            'coreg_rslc/coreg_run1',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: $product_type = RSLC
        t_coreg_rslc__coreg_run2 = orch_task(
            'coreg_run2',
            'coreg_rslc/coreg_run2',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 04b_stack_publish   when: $product_type = RSLC
        t_coreg_rslc__06_stack_publish = orch_task(
            '06_stack_publish',
            'coreg_rslc/06_stack_publish',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── coreg_gslc  (satellite coregistration) ──────────────────────────────────
    with TaskGroup(group_id='coreg_gslc') as tg_coreg_gslc:
        # step: 00b_get_dem   when: $product_type = GSLC
        t_coreg_gslc__01_get_dem = orch_task(
            '01_get_dem',
            'coreg_gslc/01_get_dem',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 01_download   when: $product_type = GSLC
        t_coreg_gslc__02_download = orch_task(
            '02_download',
            'coreg_gslc/02_download',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 02a_symlink_data   when: $product_type = GSLC
        t_coreg_gslc__03_symlink_data = orch_task(
            '03_symlink_data',
            'coreg_gslc/03_symlink_data',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 03_create_run_script   when: $product_type = GSLC
        t_coreg_gslc__04_create_run_script = orch_task(
            '04_create_run_script',
            'coreg_gslc/04_create_run_script',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: $product_type = GSLC
        t_coreg_gslc__coreg_run1g = orch_task(
            'coreg_run1g',
            'coreg_gslc/coreg_run1g',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: $product_type = GSLC
        t_coreg_gslc__coreg_run2g = orch_task(
            'coreg_run2g',
            'coreg_gslc/coreg_run2g',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 04b_stack_publish   when: $product_type = GSLC
        t_coreg_gslc__06_stack_publish = orch_task(
            '06_stack_publish',
            'coreg_gslc/06_stack_publish',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── cors  (product branch) ──────────────────────────────────────────────────
    with TaskGroup(group_id='cors') as tg_cors:
        # step: 05_generate_sarstack_runfiles   when: modes_in(dpm2, dpm3, dpm23, dpm13)
        t_cors__generate = orch_task(
            'generate',
            'cors/generate',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_params_dask_cors")
        t_cors__submit = orch_task(
            'submit',
            'cors/submit',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── icors  (product branch) ─────────────────────────────────────────────────
    with TaskGroup(group_id='icors') as tg_icors:
        # step: 05_generate_sarstack_runfiles   when: modes_in(dpm3, dpm23, dpm13)
        t_icors__generate = orch_task(
            'generate',
            'icors/generate',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_params_dask_icors")
        t_icors__submit = orch_task(
            'submit',
            'icors/submit',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── amps  (product branch) ──────────────────────────────────────────────────
    with TaskGroup(group_id='amps') as tg_amps:
        # step: 05_generate_sarstack_runfiles   when: modes_in(fpm2)
        t_amps__generate = orch_task(
            'generate',
            'amps/generate',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_params_dask_amps")
        t_amps__submit = orch_task(
            'submit',
            'amps/submit',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── ifgs  (product branch) ──────────────────────────────────────────────────
    with TaskGroup(group_id='ifgs') as tg_ifgs:
        # step: 05_generate_sarstack_runfiles   when: $generate_ifg = true
        t_ifgs__generate = orch_task(
            'generate',
            'ifgs/generate',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_params_dask_ifgs")
        t_ifgs__submit = orch_task(
            'submit',
            'ifgs/submit',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── dpm23  (product branch) ─────────────────────────────────────────────────
    with TaskGroup(group_id='dpm23') as tg_dpm23:
        # step: 05b_create_dpm23_runfiles   when: modes_in(dpm2, dpm3, dpm23)
        t_dpm23__create_dpm23_runfiles = orch_task(
            'create_dpm23_runfiles',
            'dpm23/create_dpm23_runfiles',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_ccd_1")
        t_dpm23__run_ccd_1 = orch_task(
            'run_ccd_1',
            'dpm23/run_ccd_1',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_ccd_1")
        t_dpm23__run_ccd_2 = orch_task(
            'run_ccd_2',
            'dpm23/run_ccd_2',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_ccd_1")
        t_dpm23__run_ccd_3 = orch_task(
            'run_ccd_3',
            'dpm23/run_ccd_3',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_ccd_1")
        t_dpm23__run_ccd_4 = orch_task(
            'run_ccd_4',
            'dpm23/run_ccd_4',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_ccd_1")
        t_dpm23__run_ccd_5 = orch_task(
            'run_ccd_5',
            'dpm23/run_ccd_5',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_ccd_1")
        t_dpm23__run_ccd_6 = orch_task(
            'run_ccd_6',
            'dpm23/run_ccd_6',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_ccd_1")
        t_dpm23__run_ccd_7 = orch_task(
            'run_ccd_7',
            'dpm23/run_ccd_7',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_ccd_1")
        t_dpm23__run_ccd_8 = orch_task(
            'run_ccd_8',
            'dpm23/run_ccd_8',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_icor_1")
        t_dpm23__run_icor_1 = orch_task(
            'run_icor_1',
            'dpm23/run_icor_1',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_icor_1")
        t_dpm23__run_icor_2 = orch_task(
            'run_icor_2',
            'dpm23/run_icor_2',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_icor_1")
        t_dpm23__run_icor_3 = orch_task(
            'run_icor_3',
            'dpm23/run_icor_3',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_icor_1")
        t_dpm23__run_icor_4 = orch_task(
            'run_icor_4',
            'dpm23/run_icor_4',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_icor_1")
        t_dpm23__run_icor_5 = orch_task(
            'run_icor_5',
            'dpm23/run_icor_5',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 08_dpm3_weighted_mean   when: file_exist("run_files/run_icor_1")
        t_dpm23__dpm3_weighted_mean = orch_task(
            'dpm3_weighted_mean',
            'dpm23/dpm3_weighted_mean',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: publish_product
        t_dpm23__dpm23_publish_product = orch_task(
            'dpm23_publish_product',
            'dpm23/dpm23_publish_product',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 93_upload_greyscale
        t_dpm23__upload_greyscale = orch_task(
            'upload_greyscale',
            'dpm23/upload_greyscale',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── dpm13  (product branch) ─────────────────────────────────────────────────
    with TaskGroup(group_id='dpm13') as tg_dpm13:
        # step: 05_create_dpm13_runfiles   when: modes_in(dpm13)
        t_dpm13__create_runfiles = orch_task(
            'create_runfiles',
            'dpm13/create_runfiles',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_qdpm13_icod")
        t_dpm13__run_qdpm13_1 = orch_task(
            'run_qdpm13_1',
            'dpm13/run_qdpm13_1',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: file_exist("run_files/run_qdpm13_icod")
        t_dpm13__run_qdpm13_2 = orch_task(
            'run_qdpm13_2',
            'dpm13/run_qdpm13_2',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: publish_product
        t_dpm13__publish_product = orch_task(
            'publish_product',
            'dpm13/publish_product',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── fpm  (product branch) ───────────────────────────────────────────────────
    with TaskGroup(group_id='fpm') as tg_fpm:
        # step: geocode_fpm2   when: modes_in(fpm2)
        t_fpm__geocode_fpm2 = orch_task(
            'geocode_fpm2',
            'fpm/geocode_fpm2',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: merge_fpm2   when: file_exist("run_files/run_params_dask_amps")
        t_fpm__merge_fpm2 = orch_task(
            'merge_fpm2',
            'fpm/merge_fpm2',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: publish_product
        t_fpm__fpm2_publish_product = orch_task(
            'fpm2_publish_product',
            'fpm/fpm2_publish_product',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── tail ────────────────────────────────────────────────────────────────────
    t_send_slack = slack_tail(
        slack_conn_id=SLACK_CONN_ID,
        slack_channel=SLACK_CHANNEL,
        message=SLACK_MESSAGE,
    )

    t_update_job_status = job_status_task(
        http_conn_id=HTTP_CONN_ID,
        endpoint=HTTP_ENDPOINT,
    )

    t_cleanup_variables = cleanup_variables_task()

    # ── task registry — keyed by ORCH name (see apply_customizations) ───────────
    TASKS = {
        '00_prepare_directory': t_00_prepare_directory,
        'coreg_rslc/01_get_dem': t_coreg_rslc__01_get_dem,
        'coreg_rslc/02_download': t_coreg_rslc__02_download,
        'coreg_rslc/03_symlink_data': t_coreg_rslc__03_symlink_data,
        'coreg_rslc/04_create_run_script': t_coreg_rslc__04_create_run_script,
        'coreg_rslc/coreg_run1': t_coreg_rslc__coreg_run1,
        'coreg_rslc/coreg_run2': t_coreg_rslc__coreg_run2,
        'coreg_rslc/06_stack_publish': t_coreg_rslc__06_stack_publish,
        'coreg_gslc/01_get_dem': t_coreg_gslc__01_get_dem,
        'coreg_gslc/02_download': t_coreg_gslc__02_download,
        'coreg_gslc/03_symlink_data': t_coreg_gslc__03_symlink_data,
        'coreg_gslc/04_create_run_script': t_coreg_gslc__04_create_run_script,
        'coreg_gslc/coreg_run1g': t_coreg_gslc__coreg_run1g,
        'coreg_gslc/coreg_run2g': t_coreg_gslc__coreg_run2g,
        'coreg_gslc/06_stack_publish': t_coreg_gslc__06_stack_publish,
        'cors/generate': t_cors__generate,
        'cors/submit': t_cors__submit,
        'icors/generate': t_icors__generate,
        'icors/submit': t_icors__submit,
        'amps/generate': t_amps__generate,
        'amps/submit': t_amps__submit,
        'ifgs/generate': t_ifgs__generate,
        'ifgs/submit': t_ifgs__submit,
        'dpm23/create_dpm23_runfiles': t_dpm23__create_dpm23_runfiles,
        'dpm23/run_ccd_1': t_dpm23__run_ccd_1,
        'dpm23/run_ccd_2': t_dpm23__run_ccd_2,
        'dpm23/run_ccd_3': t_dpm23__run_ccd_3,
        'dpm23/run_ccd_4': t_dpm23__run_ccd_4,
        'dpm23/run_ccd_5': t_dpm23__run_ccd_5,
        'dpm23/run_ccd_6': t_dpm23__run_ccd_6,
        'dpm23/run_ccd_7': t_dpm23__run_ccd_7,
        'dpm23/run_ccd_8': t_dpm23__run_ccd_8,
        'dpm23/run_icor_1': t_dpm23__run_icor_1,
        'dpm23/run_icor_2': t_dpm23__run_icor_2,
        'dpm23/run_icor_3': t_dpm23__run_icor_3,
        'dpm23/run_icor_4': t_dpm23__run_icor_4,
        'dpm23/run_icor_5': t_dpm23__run_icor_5,
        'dpm23/dpm3_weighted_mean': t_dpm23__dpm3_weighted_mean,
        'dpm23/dpm23_publish_product': t_dpm23__dpm23_publish_product,
        'dpm23/upload_greyscale': t_dpm23__upload_greyscale,
        'dpm13/create_runfiles': t_dpm13__create_runfiles,
        'dpm13/run_qdpm13_1': t_dpm13__run_qdpm13_1,
        'dpm13/run_qdpm13_2': t_dpm13__run_qdpm13_2,
        'dpm13/publish_product': t_dpm13__publish_product,
        'fpm/geocode_fpm2': t_fpm__geocode_fpm2,
        'fpm/merge_fpm2': t_fpm__merge_fpm2,
        'fpm/fpm2_publish_product': t_fpm__fpm2_publish_product,
    }

    # ── wiring — mirrors the pipeline `needs:` DAG, one edge per line ───────────
    # Head: nothing can run before the payload is in place.
    t_set_variables >> t_00_prepare_directory

    t_00_prepare_directory >> t_coreg_rslc__01_get_dem
    t_coreg_rslc__01_get_dem >> t_coreg_rslc__02_download
    t_coreg_rslc__02_download >> t_coreg_rslc__03_symlink_data
    t_coreg_rslc__03_symlink_data >> t_coreg_rslc__04_create_run_script
    t_coreg_rslc__04_create_run_script >> t_coreg_rslc__coreg_run1
    t_coreg_rslc__coreg_run1 >> t_coreg_rslc__coreg_run2
    t_coreg_rslc__coreg_run2 >> t_coreg_rslc__06_stack_publish
    t_00_prepare_directory >> t_coreg_gslc__01_get_dem
    t_coreg_gslc__01_get_dem >> t_coreg_gslc__02_download
    t_coreg_gslc__02_download >> t_coreg_gslc__03_symlink_data
    t_coreg_gslc__03_symlink_data >> t_coreg_gslc__04_create_run_script
    t_coreg_gslc__04_create_run_script >> t_coreg_gslc__coreg_run1g
    t_coreg_gslc__coreg_run1g >> t_coreg_gslc__coreg_run2g
    t_coreg_gslc__coreg_run2g >> t_coreg_gslc__06_stack_publish
    t_coreg_rslc__06_stack_publish >> t_cors__generate
    t_coreg_gslc__06_stack_publish >> t_cors__generate
    t_cors__generate >> t_cors__submit
    t_coreg_rslc__06_stack_publish >> t_icors__generate
    t_coreg_gslc__06_stack_publish >> t_icors__generate
    t_icors__generate >> t_icors__submit
    t_coreg_rslc__06_stack_publish >> t_amps__generate
    t_coreg_gslc__06_stack_publish >> t_amps__generate
    t_amps__generate >> t_amps__submit
    t_coreg_rslc__06_stack_publish >> t_ifgs__generate
    t_coreg_gslc__06_stack_publish >> t_ifgs__generate
    t_ifgs__generate >> t_ifgs__submit
    t_cors__submit >> t_dpm23__create_dpm23_runfiles
    t_icors__submit >> t_dpm23__create_dpm23_runfiles
    t_dpm23__create_dpm23_runfiles >> t_dpm23__run_ccd_1
    t_dpm23__run_ccd_1 >> t_dpm23__run_ccd_2
    t_dpm23__run_ccd_2 >> t_dpm23__run_ccd_3
    t_dpm23__run_ccd_3 >> t_dpm23__run_ccd_4
    t_dpm23__run_ccd_4 >> t_dpm23__run_ccd_5
    t_dpm23__run_ccd_5 >> t_dpm23__run_ccd_6
    t_dpm23__run_ccd_6 >> t_dpm23__run_ccd_7
    t_dpm23__run_ccd_7 >> t_dpm23__run_ccd_8
    t_dpm23__create_dpm23_runfiles >> t_dpm23__run_icor_1
    t_dpm23__run_icor_1 >> t_dpm23__run_icor_2
    t_dpm23__run_icor_2 >> t_dpm23__run_icor_3
    t_dpm23__run_icor_3 >> t_dpm23__run_icor_4
    t_dpm23__run_icor_4 >> t_dpm23__run_icor_5
    t_dpm23__run_ccd_8 >> t_dpm23__dpm3_weighted_mean
    t_dpm23__run_icor_5 >> t_dpm23__dpm3_weighted_mean
    t_dpm23__dpm3_weighted_mean >> t_dpm23__dpm23_publish_product
    t_dpm23__dpm23_publish_product >> t_dpm23__upload_greyscale
    t_cors__submit >> t_dpm13__create_runfiles
    t_icors__submit >> t_dpm13__create_runfiles
    t_dpm13__create_runfiles >> t_dpm13__run_qdpm13_1
    t_dpm13__run_qdpm13_1 >> t_dpm13__run_qdpm13_2
    t_dpm13__run_qdpm13_2 >> t_dpm13__publish_product
    t_amps__submit >> t_fpm__geocode_fpm2
    t_fpm__geocode_fpm2 >> t_fpm__merge_fpm2
    t_fpm__merge_fpm2 >> t_fpm__fpm2_publish_product

    # Tail: every branch tip converges on the notification chain.
    t_ifgs__submit >> t_send_slack
    t_dpm23__upload_greyscale >> t_send_slack
    t_dpm13__publish_product >> t_send_slack
    t_fpm__fpm2_publish_product >> t_send_slack
    t_send_slack >> t_update_job_status
    t_update_job_status >> t_cleanup_variables

    # Structural per-DAG customization, if the operator wrote a sidecar.
    apply_customizations(dag, TASKS, dag_id=DAG_ID)
