# ────────────────────────────────────────────────────────────────────────────
# GENERATED by `orch gen-dag nisar_dyn` — DO NOT EDIT.
# Source:    orch/workflow/pipelines/nisar_dyn.yaml  (22 tasks)
# Settings:  orch/workflow/airflow/dags.yaml
# Generator: version 1
#
# To change the graph, edit the pipeline YAML and re-run `orch gen-dag`.
# To change THIS DAG only, write customize_NISAR_DYN.py in this
# folder (see orch_dag_common.apply_customizations) — the generator
# never touches that file.
# ────────────────────────────────────────────────────────────────────────────
"""NISAR_DYN — generated from the nisar_dyn orch pipeline."""

from datetime import datetime

from airflow import DAG
from airflow.utils.task_group import TaskGroup

from orch_dag_common import (
    apply_customizations,
    cleanup_variables_task,
    job_status_task,
    make_failure_callback,
    orch_init_task,
    orch_task,
    set_variables_task,
    slack_tail,
)


DAG_ID = 'NISAR_DYN'
PIPELINE = 'nisar_dyn'
REPO = '/home/ubuntu/insarscripts/stack_processor_aws_dev'
WORK_ROOT = '/home/ubuntu/urgent_response'
SETUP_CMD = 'source /home/ubuntu/insarscripts/stack_processor_aws_dev/env_setup/setup_env.sh nisar_dyn'
SSH_CONN_ID = 'ssh'
HTTP_CONN_ID = 'sarfinder'
HTTP_ENDPOINT = 'api/sarfinder/airflow/task/update/'
SLACK_CONN_ID = 'slack_webhook_dpm2'
SLACK_CHANNEL = '#dpm2-sarfinder-aws-hpc'
SLACK_MESSAGE = ':blob_excited: NISAR_DYN products are ready. On your MacBook:\n```\nscp -r aws-hpc2:/home/ubuntu/urgent_response/{{ var.json[run_id].dir_name }}/products .\n```\n'


failure_callback = make_failure_callback(
    slack_conn_id=SLACK_CONN_ID,
    slack_channel=SLACK_CHANNEL,
    http_conn_id=HTTP_CONN_ID,
    http_endpoint=HTTP_ENDPOINT,
)


with DAG(
    dag_id=DAG_ID,
    schedule_interval=None,
    start_date=datetime(2022, 1, 1),
    catchup=False,
    default_args={'retries': 0, 'on_failure_callback': failure_callback},
    on_failure_callback=failure_callback,
) as dag:
    # The run payload (dir_name, modes, bbox, dates, …) reaches every
    # task through the run-id Variable this sets.
    t_set_variables = set_variables_task(DAG_ID)

    # ── stack_init  (satellite coregistration) ──────────────────────────────────
    with TaskGroup(group_id='stack_init') as tg_stack_init:
        # step: 00a_prepare_directory
        t_stack_init__00_prepare_directory = orch_init_task(
            '00_prepare_directory',
            pipeline=PIPELINE,
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 00b_get_dem
        t_stack_init__01_get_dem = orch_task(
            '01_get_dem',
            'stack_init/01_get_dem',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 01_download
        t_stack_init__02_download = orch_task(
            '02_download',
            'stack_init/02_download',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 02a_symlink_data
        t_stack_init__03_symlink_data = orch_task(
            '03_symlink_data',
            'stack_init/03_symlink_data',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 03_create_run_script
        t_stack_init__04_create_run_script = orch_task(
            '04_create_run_script',
            'stack_init/04_create_run_script',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run
        t_stack_init__05_execute_coreg_runs = orch_task(
            '05_execute_coreg_runs',
            'stack_init/05_execute_coreg_runs',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 04b_stack_publish
        t_stack_init__06_stack_publish = orch_task(
            '06_stack_publish',
            'stack_init/06_stack_publish',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── dpm23  (product branch) ─────────────────────────────────────────────────
    with TaskGroup(group_id='dpm23') as tg_dpm23:
        # step: 05b_create_dpm23_runfiles   when: mode:dpm23
        t_dpm23__create_dpm23_runfiles = orch_task(
            'create_dpm23_runfiles',
            'dpm23/create_dpm23_runfiles',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: run_files/run_ccd_1
        t_dpm23__run_dpm_ccd = orch_task(
            'run_dpm_ccd',
            'dpm23/run_dpm_ccd',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: exe_run   when: run_files/run_icor_1
        t_dpm23__run_dpm_iccd = orch_task(
            'run_dpm_iccd',
            'dpm23/run_dpm_iccd',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 08_dpm3_weighted_mean   when: run_files/run_icor_1
        t_dpm23__dpm3_weighted_mean = orch_task(
            'dpm3_weighted_mean',
            'dpm23/dpm3_weighted_mean',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: publish_product
        t_dpm23__dpm23_publish_product = orch_task(
            'dpm23_publish_product',
            'dpm23/dpm23_publish_product',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: 93_upload_greyscale
        t_dpm23__upload_greyscale = orch_task(
            'upload_greyscale',
            'dpm23/upload_greyscale',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── fpm  (product branch) ───────────────────────────────────────────────────
    with TaskGroup(group_id='fpm') as tg_fpm:
        # step: geocode_fpm2
        t_fpm__geocode_fpm2 = orch_task(
            'geocode_fpm2',
            'fpm/geocode_fpm2',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: merge_fpm2   when: run_files/run_params_dask_amps
        t_fpm__merge_fpm2 = orch_task(
            'merge_fpm2',
            'fpm/merge_fpm2',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

        # step: publish_product
        t_fpm__fpm2_publish_product = orch_task(
            'fpm2_publish_product',
            'fpm/fpm2_publish_product',
            ssh_conn_id=SSH_CONN_ID,
            setup_cmd=SETUP_CMD,
            work_root=WORK_ROOT,
        )

    # ── top-level pipeline tasks ────────────────────────────────────────────────
    # step: 05_generate_sarstack_runfiles
    t_generate_cor_runfiles = orch_task(
        'generate_cor_runfiles',
        'generate_cor_runfiles',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: exe_run   when: run_files/run_params_dask_cors
    t_run_cors = orch_task(
        'run_cors',
        'run_cors',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: exe_run   when: run_files/run_params_dask_icors
    t_run_icors = orch_task(
        'run_icors',
        'run_icors',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 05_create_dpm13_runfiles
    t_create_dpm13_runfiles = orch_task(
        'create_dpm13_runfiles',
        'create_dpm13_runfiles',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: 05_generate_sarstack_runfiles
    t_generate_amps_runfiles = orch_task(
        'generate_amps_runfiles',
        'generate_amps_runfiles',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # step: exe_run   when: run_files/run_params_dask_amps
    t_run_amps = orch_task(
        'run_amps',
        'run_amps',
        ssh_conn_id=SSH_CONN_ID,
        setup_cmd=SETUP_CMD,
        work_root=WORK_ROOT,
    )

    # ── tail ────────────────────────────────────────────────────────────────────
    t_send_slack = slack_tail(
        slack_conn_id=SLACK_CONN_ID,
        slack_channel=SLACK_CHANNEL,
        message=SLACK_MESSAGE,
    )

    t_update_job_status = job_status_task(
        http_conn_id=HTTP_CONN_ID,
        endpoint=HTTP_ENDPOINT,
    )

    t_cleanup_variables = cleanup_variables_task()

    # ── task registry — keyed by ORCH name (see apply_customizations) ───────────
    TASKS = {
        'stack_init/00_prepare_directory': t_stack_init__00_prepare_directory,
        'stack_init/01_get_dem': t_stack_init__01_get_dem,
        'stack_init/02_download': t_stack_init__02_download,
        'stack_init/03_symlink_data': t_stack_init__03_symlink_data,
        'stack_init/04_create_run_script': t_stack_init__04_create_run_script,
        'stack_init/05_execute_coreg_runs': t_stack_init__05_execute_coreg_runs,
        'stack_init/06_stack_publish': t_stack_init__06_stack_publish,
        'generate_cor_runfiles': t_generate_cor_runfiles,
        'run_cors': t_run_cors,
        'run_icors': t_run_icors,
        'dpm23/create_dpm23_runfiles': t_dpm23__create_dpm23_runfiles,
        'dpm23/run_dpm_ccd': t_dpm23__run_dpm_ccd,
        'dpm23/run_dpm_iccd': t_dpm23__run_dpm_iccd,
        'dpm23/dpm3_weighted_mean': t_dpm23__dpm3_weighted_mean,
        'dpm23/dpm23_publish_product': t_dpm23__dpm23_publish_product,
        'dpm23/upload_greyscale': t_dpm23__upload_greyscale,
        'create_dpm13_runfiles': t_create_dpm13_runfiles,
        'generate_amps_runfiles': t_generate_amps_runfiles,
        'run_amps': t_run_amps,
        'fpm/geocode_fpm2': t_fpm__geocode_fpm2,
        'fpm/merge_fpm2': t_fpm__merge_fpm2,
        'fpm/fpm2_publish_product': t_fpm__fpm2_publish_product,
    }

    # ── wiring — mirrors the pipeline `needs:` DAG, one edge per line ───────────
    # Head: nothing can run before the payload is in place.
    t_set_variables >> t_stack_init__00_prepare_directory

    t_stack_init__00_prepare_directory >> t_stack_init__01_get_dem
    t_stack_init__01_get_dem >> t_stack_init__02_download
    t_stack_init__02_download >> t_stack_init__03_symlink_data
    t_stack_init__03_symlink_data >> t_stack_init__04_create_run_script
    t_stack_init__04_create_run_script >> t_stack_init__05_execute_coreg_runs
    t_stack_init__05_execute_coreg_runs >> t_stack_init__06_stack_publish
    t_stack_init__06_stack_publish >> t_generate_cor_runfiles
    t_generate_cor_runfiles >> t_run_cors
    t_generate_cor_runfiles >> t_run_icors
    t_run_cors >> t_dpm23__create_dpm23_runfiles
    t_run_icors >> t_dpm23__create_dpm23_runfiles
    t_dpm23__create_dpm23_runfiles >> t_dpm23__run_dpm_ccd
    t_dpm23__create_dpm23_runfiles >> t_dpm23__run_dpm_iccd
    t_dpm23__run_dpm_ccd >> t_dpm23__dpm3_weighted_mean
    t_dpm23__run_dpm_iccd >> t_dpm23__dpm3_weighted_mean
    t_dpm23__dpm3_weighted_mean >> t_dpm23__dpm23_publish_product
    t_dpm23__dpm23_publish_product >> t_dpm23__upload_greyscale
    t_run_cors >> t_create_dpm13_runfiles
    t_run_icors >> t_create_dpm13_runfiles
    t_stack_init__06_stack_publish >> t_generate_amps_runfiles
    t_generate_amps_runfiles >> t_run_amps
    t_run_amps >> t_fpm__geocode_fpm2
    t_fpm__geocode_fpm2 >> t_fpm__merge_fpm2
    t_fpm__merge_fpm2 >> t_fpm__fpm2_publish_product

    # Tail: every branch tip converges on the notification chain.
    t_dpm23__upload_greyscale >> t_send_slack
    t_create_dpm13_runfiles >> t_send_slack
    t_fpm__fpm2_publish_product >> t_send_slack
    t_send_slack >> t_update_job_status
    t_update_job_status >> t_cleanup_variables

    # Structural per-DAG customization, if the operator wrote a sidecar.
    apply_customizations(dag, TASKS, dag_id=DAG_ID)
