# ────────────────────────────────────────────────────────────────────────────
# COPIED by `orch gen-dag` from orch/workflow/airflow/orch_dag_common.py
# Generator: version 1
# Edit it there and re-run `orch gen-dag` — DO NOT EDIT HERE.
# ────────────────────────────────────────────────────────────────────────────
"""Shared plumbing for orch-generated Airflow DAGs.

This file is copied verbatim into the Airflow dags folder by ``orch gen-dag``.
It is the single home for everything the 14 hand-written DAGs used to duplicate:
the SSH command shape, the failure callback, the Variable dance, and the
Slack → job-status → cleanup tail.

It is also the ONLY place that knows about Airflow version differences. Keep
provider shims here so a generated DAG never has to change when the host's
Airflow is upgraded.

Do not edit this file in the dags folder — edit
``orch/workflow/airflow/orch_dag_common.py`` in stack_processor_aws_dev and
re-run ``orch gen-dag``.
"""
from __future__ import annotations

import importlib
import json

import requests
from airflow.models import Variable
from airflow.operators.python import PythonOperator
from airflow.providers.slack.operators.slack_webhook import SlackWebhookOperator
from airflow.providers.ssh.operators.ssh import SSHOperator

# http provider >= 5 renamed SimpleHttpOperator -> HttpOperator.
try:  # pragma: no cover - depends on the host's provider version
    from airflow.providers.http.operators.http import SimpleHttpOperator
except ImportError:  # pragma: no cover
    from airflow.providers.http.operators.http import HttpOperator as SimpleHttpOperator

# The job dir name for this run, as an Airflow template expression. Every task
# except the init one cd's into WORK_ROOT/<this>.
DIR_NAME = "{{ var.json[run_id].dir_name }}"

# The whole run-id Variable payload (the JSON blob SARFinder wrote).
RUN_PAYLOAD = "{{ var.value[run_id] }}"

INIT_STEP = "00a_prepare_directory"


# ── command construction ─────────────────────────────────────────────────────


def ssh_cmd(script: str, *, setup_cmd: str, work_root: str, use_dir: bool = True) -> str:
    """Build the remote command: source the env, optionally cd into the job dir.

    ``use_dir=False`` is for the init step, which runs before the job dir (and
    its config.txt) exists.
    """
    base = setup_cmd
    if use_dir:
        base += f"; cd {work_root}/{DIR_NAME}"
    return f"{base}; {script}"


def orch_task(task_id, orch_name, *, ssh_conn_id, setup_cmd, work_root, **kwargs):
    """One Airflow task = one orch pipeline task.

    Runs ``orch run <name> <name>`` rather than ``orch run-step``: the ``run``
    path substitutes ``${key}`` argv against config.txt, evaluates the task's
    ``when:`` gates (a gated-out task is recorded ``skipped`` and exits 0, so it
    shows green in Airflow), records the manifest entry, and tees output to
    ``log/orch/<name>.log``. ``run-step`` does none of that.

    ``orch_name`` is the orch task id and may contain ``/`` (block namespacing);
    ``task_id`` is the Airflow id within its TaskGroup and may not.
    """
    kwargs.setdefault("cmd_timeout", None)
    kwargs.setdefault("conn_timeout", None)
    return SSHOperator(
        task_id=task_id,
        ssh_conn_id=ssh_conn_id,
        command=ssh_cmd(
            f"orch run '{orch_name}' '{orch_name}' --job-dir .",
            setup_cmd=setup_cmd,
            work_root=work_root,
        ),
        **kwargs,
    )


def orch_init_task(task_id, *, pipeline, ssh_conn_id, setup_cmd, work_root, **kwargs):
    """The init task — the one exception to the ``orch run`` rule.

    ``00a_prepare_directory`` creates the job dir, so it cannot cd into it, and
    there is no config.txt yet to substitute against. It takes the run payload
    as ``--json``; the ``export VARIABLE=$(... | tr -d '\\n')`` hop (inherited
    from the hand-written DAGs) gets the JSON blob past two layers of shell
    quoting. ``--root`` is absolute so 00a's nesting guard can never trip.
    """
    kwargs.setdefault("cmd_timeout", None)
    kwargs.setdefault("conn_timeout", None)
    body = (
        f"export VARIABLE=$(echo '{RUN_PAYLOAD}' | tr -d '\\n') && "
        f"orch run-step {INIT_STEP} -- "
        f"--root {work_root} --pipeline {pipeline} --json \"$VARIABLE\""
    )
    return SSHOperator(
        task_id=task_id,
        ssh_conn_id=ssh_conn_id,
        command=ssh_cmd(body, setup_cmd=setup_cmd, work_root=work_root, use_dir=False),
        **kwargs,
    )


# ── failure handling ─────────────────────────────────────────────────────────


def make_failure_callback(*, slack_conn_id, slack_channel, http_conn_id, http_endpoint):
    """Build the on-failure callback: Slack alert, then mark the job failed.

    A factory rather than a module-level function because the Slack connection
    and channel now vary per DAG.
    """

    def failure_callback(context):
        dag_run = context.get("dag_run")
        dag_run_id = dag_run.run_id if dag_run else "unknown"
        ti = context.get("task_instance")

        try:
            slack_msg = f"""
            :red_circle: Task Failed. Please go to Airflow for more details.
            *Task*: {ti.task_id if ti else "unknown"}
            *Dag*: {ti.dag_id if ti else "unknown"}
            *Execution Time*: {context.get("execution_date")}
            *Log Url*: {ti.log_url if ti else "unknown"}
        """
            SlackWebhookOperator(
                task_id="slack_failed_alert",
                slack_webhook_conn_id=slack_conn_id,
                message=slack_msg,
                username="airflow",
                channel=slack_channel,
            ).execute(context=context)
        except Exception as slack_error:  # noqa: BLE001 - never mask the real failure
            print(f"Failed to send Slack alert: {slack_error}")

        try:
            SimpleHttpOperator(
                task_id="update_job_status",
                http_conn_id=http_conn_id,
                endpoint=http_endpoint,
                method="POST",
                headers={"Content-Type": "application/json"},
                data=json.dumps({"status": "failed", "dag_run_id": "{{ run_id }}"}),
            ).execute(context=context)
            print(f"Updated status to failed for DAG run {dag_run_id}")
        except requests.RequestException as http_error:
            print(f"Failed to update job status: {http_error}")

    return failure_callback


# ── run payload plumbing ─────────────────────────────────────────────────────


def set_variables_task(dag_id: str):
    """Copy this run's payload into a Variable keyed by ``run_id``.

    Prefers ``dag_run.conf`` (what a trigger passes directly) and falls back to
    the legacy ``{DAG_ID}_variables`` Variable. The fallback races when two runs
    of the same DAG are triggered close together — which the old
    satellite x product DAG matrix made unlikely and the collapse to one DAG per
    satellite makes likely. Passing the payload as trigger conf avoids it.
    """

    def set_variables(**kwargs):
        dag_run = kwargs.get("dag_run")
        conf = (dag_run.conf or {}) if dag_run else {}
        payload = json.dumps(conf) if conf else Variable.get(f"{dag_id}_variables")
        Variable.set(kwargs["run_id"], payload)
        return payload

    return PythonOperator(
        task_id="set_variables",
        python_callable=set_variables,
        provide_context=True,
    )


def cleanup_variables_task():
    def cleanup_variables(**kwargs):
        Variable.delete(kwargs["run_id"])

    return PythonOperator(
        task_id="cleanup_variables",
        python_callable=cleanup_variables,
        provide_context=True,
    )


# ── tail ─────────────────────────────────────────────────────────────────────


def slack_tail(*, slack_conn_id, slack_channel, message):
    return SlackWebhookOperator(
        task_id="send_slack_notifications",
        slack_webhook_conn_id=slack_conn_id,
        message=message,
        channel=slack_channel,
        username="airflow",
    )


def job_status_task(*, http_conn_id, endpoint, status="success"):
    return SimpleHttpOperator(
        task_id="update_job_status",
        http_conn_id=http_conn_id,
        endpoint=endpoint,
        method="POST",
        headers={"Content-Type": "application/json"},
        data=json.dumps({"status": status, "dag_run_id": "{{ run_id }}"}),
        extra_options={"check_response": False},
    )


# ── customization escape hatch ───────────────────────────────────────────────


def apply_customizations(dag, tasks: dict, *, dag_id: str) -> None:
    """Hand control to ``customize_<DAG_ID>.py`` if the operator wrote one.

    That module defines ``customize(dag, tasks)`` and can add tasks, rewire
    edges, or change trigger rules. ``orch gen-dag`` never writes or deletes it,
    so structural customization survives regeneration.

    ``tasks`` is keyed by ORCH task name (``dpm23/run_dpm_ccd``), not the
    Airflow id — deliberately, so renaming a pipeline task surfaces as a
    KeyError at DAG-parse time instead of silently dropping a customization.
    """
    try:
        module = importlib.import_module(f"customize_{dag_id}")
    except ImportError:
        return
    hook = getattr(module, "customize", None)
    if hook is not None:
        hook(dag, tasks)
